language: go
sudo: false
install: true
os:
  - linux
  - osx
go:
  - 1.6.3
  - 1.7.3
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  matrix:
    - GOARCH=amd64
    - GOARCH=386
script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - ./lint.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip
