language: go
sudo: false
install: true
os:
  - linux
  - osx
go:
  - 1.9.x
  - 1.10.x
  - tip
env:
  matrix:
    - GOARCH=amd64
    - GOARCH=386
script:
  - make lint coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip
